### ISSUE TITLE
Hologram can not display itemname

### ISSUE THREAD

**Issue by Ezesty** [Flowsqy/ShopChest#22]
![image](https://github.com/Flowsqy/ShopChest/assets/147943750/6c1acaba-ffe0-4945-a5ca-0f01dc06e885)
Hologram can not display itemname
how to repair it

**Comment by Flowsqy** [comment]
Look at the Usage section of the Readme. (Main GitHub page). You simply didn't configure the item language file.

**Comment by Ezesty** [comment]
Do you have any video tutorial? Because my english is so bad

**Comment by Ezesty** [comment]
And i dont understand what i should do with lang

**Comment by Flowsqy** [comment]
No :/. Try to use a translator.

**Comment by Ezesty** [comment]
I have something this
My last task which i making was
Open a command prompt. Then type gradlew assembleDist on Windows or ./gradlew assembleDist on Linux and macOS 

Now i dont have
Go to the app/build/distributions folder
![Zrzut ekranu (324)](https://github.com/Flowsqy/ShopChest/assets/147943750/93836ce4-c55b-49f7-98bc-4c32aac7880b)
![Zrzut ekranu (325)](https://github.com/Flowsqy/ShopChest/assets/147943750/22b736eb-f91f-46b3-858c-8ddf607353ea)

**Comment by Flowsqy** [comment]
https://youtu.be/DYMR4fMmgnM

**Comment by Ezesty** [comment]
Ohhh thanks now work <3
I was must only download java 17 because this warning i get in cmd after send command
I would never do this with the readme myself
I have the impression from your video that there is something completely different there than in the readme

**Comment by Flowsqy** [comment]
Yeah, it's another way to do it.

**Comment by Ezesty** [comment]
How to change from $1.0 for $1 ??

**Comment by Flowsqy** [comment]
You can't. It's planned for the rewrite.
