### ISSUE TITLE
1.20.4  "Not Configured" as all item names

### ISSUE THREAD

**Issue by Codewow** [Flowsqy/ShopChest#24]
No matter what item we add to shops, it shows the name "Unconfigured." Tested on Papermc # 370 with your latest release.

![image](https://github.com/Flowsqy/ShopChest/assets/8216811/ba1d9239-026f-4e57-88c8-0089a145683e)

**Comment by Flowsqy** [comment]
Look at the README and the warnings in the logs. You have to configure item names.
