### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by AlexanderMoebius** [Flowsqy/ShopChest#26]
Since 1.20.5 there had been changes in the requirements for compiling the plugin.
Can you please update the readme with the required mvn and java version?

**Comment by Flowsqy** [comment]
Afaik, it does not require any specific java version or maven version. (You just need java 8+). I fixed the nms readme (it does not require 1.20.5 but 1.20.6). What's your problem exactly ?

**Comment by AlexanderMoebius** [comment]
Oh.

The first problem with `mvn clean install` is that the nms module for 1.20.6 is not recognized:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project shopchest-plugin: Compilation failure
[ERROR] /C:/Users/alexa/workspace/MC/ShopChest-GamesMC/plugin/src/main/java/de/epiceric/shopchest/nms/PlatformLoader.java:[102,62] package de.epiceric.shopchest.nms.v1_20_R4 does not exist
```
When I try to install the nms module explicitly first, the new EntityType.ITEM is not found.
The Problems because of those I thought it is the java version (Incompatible Version 65) came later when I tried all possible things.

For sure spigot 1.20.6 remapped is compiled and installed to the local maven repo.
The github token is in the maven config and valid.

**Comment by Flowsqy** [comment]
Oh, I didn't update the package on GitHub so you need to build the nms artifact yourself (with the -DbuildNMS option).
I'm gonna investigate this real quick.

**Comment by Flowsqy** [comment]
It runs fine for me with the -DbuildNMS option, java 21.0.1 and maven 3.9.7. I will upload the nms artifact to GitHub package anyway.

**Comment by AlexanderMoebius** [comment]
Thanks.
I wonder why the nms wont compile 
```
[ERROR] /C:/Users/alexa/workspace/MC/ShopChest-GamesMC/nms/reflection/src/main/java/de/epiceric/shopchest/nms/reflection/FakeItemImpl.java:[46,30] cannot find symbol
[ERROR]   symbol:   variable ITEM
[ERROR]   location: class org.bukkit.entity.EntityType
```
But when it loads the package from github, it wont be a problem anymore. Maybe a task for the future me...

Thanks for the quick help!

**Comment by Flowsqy** [comment]
Pretty strange indeed. I've updated the package and tested it, it works fine. You should be okay until 1.21 :D
