### ISSUE TITLE
Having issues running on 1.21 purpur

### ISSUE THREAD

**Issue by jamesmckubre** [Flowsqy/ShopChest#29]
When starting server i am met with the message 

[18:35:35 WARN]: [ShopChest] Server version not officially supported. Version: 'craftbukkit', Mappings : '229d7afc75b70a6c388337687ac4da1f'
>....
[18:35:35 WARN]: [ShopChest] Disabling the plugin

what can I do to avoid this. And get the plugin running.

Cheers.

**Comment by Flowsqy** [comment]
You need to have the latest release of the plugin to support 1.21. You can get it [here](https://github.com/Flowsqy/ShopChest/releases/tag/v1.14.0-SNAPSHOT-1.21)

**Comment by jamesmckubre** [comment]
Thanks, but that's where I get confused as that is the version I am currently running. Is it something Purpur related.

**Comment by Flowsqy** [comment]
The error message tells that this Minecraft version is not supported. However, when looking at the code, it clearly is and this should run fine. I will test it on a purpur server but if it doesn't work then it's some kind of black magic.

**Comment by Flowsqy** [comment]
The plugin loads fine with purpur 1.21-2256-de2e7a7 and the latest ShopChest release. Try it on a fresh server and ensure you got the right jar.
