### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by tooop4u** [Flowsqy/ShopChest#3]
Hi, would be appreciated if you added support for 1.18.2 because it isn't working as of now

Thank you

**Comment by Flowsqy** [comment]
Done. :D You can fin the release [here](https://github.com/Flowsqy/ShopChest/releases/tag/v1.14.0-SNAPSHOT-1.18.2)

**Comment by tooop4u** [comment]
Thank your for the quick update!
