### ISSUE TITLE
Maven compilation error

### ISSUE THREAD

**Issue by AlexanderMoebius** [Flowsqy/ShopChest#5]
Hey,

first of all thanks that there is a version for 1.18.2 :)
But when I try to compile the plugin the repository maven.wiefferink.me can not be reached and the area shop dependency therefore can not be loaded.

**Comment by Flowsqy** [comment]
Hi !
I will check this in few hours. As Areashop is not officially maintened anymore, it's possible that the maven repository expired. If you want a .jar as fast as possible, you can find one in the release section.

**Comment by AlexanderMoebius** [comment]
Thanks.
I will try it If it takes longer.
My aim way to also modify this fork Like i modified the original (for example with accepting every Container as Shop) so also barrels kann bei used.

**Comment by Flowsqy** [comment]
Oh nice !
If you want to fork it, note that every PR is welcomed. 
Few things to know:
- There is the branch called "dani-fork" which include the work from @[DaniFoldi](https://github.com/DaniFoldi) where there is barrel support, async vault call and other cool features
- There us the branch called "external-module" which aim to improve integration and rebuild them from scratch. I'm not sure about which integration I will keep as most plugins are unmaintained. But It will be the master branch when the work will be done, so you can consider it as a "dev" branch. It's probably better to make your fork around this, but using the "master" branch will also work as the "plugin" module will not change.

**Comment by Flowsqy** [comment]
I checked and it seems that the server that host the "official" public repository (and the personal website of the author) is down. I don't know for how long, so I will leave it like this. If you want to modify the plugin, start from the "external-module" branch, there will be no "weird" dependency and no problem with compiling.

**Comment by AlexanderMoebius** [comment]
Got it now. A little bit tricky so I will probably add some more explanation to the readme 😅

But is it possible that the MySQL Connection is messed up? Or am I just doing anything completely wrong?

And do you have a discord or anything else to not just write here in GitHub?

**Comment by Flowsqy** [comment]
After verification, MySQL seems to work properly.
 There is branch called 'fix/areashop-dependency' to fix the original issue. 
 This thread is pretty old and now outdated, I close it.
