### ISSUE TITLE
1.19.2 support 

### ISSUE THREAD

**Issue by Niko302** [Flowsqy/ShopChest#9]
Hey, first I want to say thank you so much for making the code public where you added support for more recent versions of ShopChest.

It would be amazing if you could add support for "DECENT HOLOGRAMS" the same way they work with Holographic Display since its a more active plugin and has a lot more features that holographic display does not offer and its just more clean in a lot of ways.

Decent Holograms spigot page: https://www.spigotmc.org/resources/decent-holograms-1-8-1-19-papi-support-no-dependencies.96927/

Kind Regads,
Niko

**Comment by Flowsqy** [comment]
Hi!
Making the code public seemed logic as the original plugin was public as well. But you're welcome. :D
For your suggestion, what do you mean exaclty by "DecentHologram support" ? I don't see the link between this plugin and ShopChest as it's a Hologram plugin and ShopChest handle that by its own.

**Comment by Flowsqy** [comment]
For 1.19.2 support, it will be released when I will be back home (in 4 or 5 days)

**Comment by Niko302** [comment]
> 

Oh, sorry my bad for a second thought it was linked to that but later figured out it was the 1.19.2 that was messing with the startup. Ty for the quick reply.

**Comment by Flowsqy** [comment]
Done
